//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Data.Objects.DataClasses.EdmSchemaAttribute()]

// Original file name:
// Generation date: 07-Jul-17 8:24:16 PM
namespace sifibiModel
{
    
    /// <summary>
    /// There are no comments for sifibiModel.user in the schema.
    /// </summary>
    /// <KeyProperties>
    /// id_user
    /// </KeyProperties>
    [global::System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName="sifibiModel", Name="user")]
    [global::System.Runtime.Serialization.DataContractAttribute(IsReference=true)]
    [global::System.Serializable()]
    public partial class user : global::System.Data.Objects.DataClasses.EntityObject
    {
        /// <summary>
        /// Create a new user object.
        /// </summary>
        /// <param name="id_user">Initial value of id_user.</param>
        /// <param name="nama_user">Initial value of nama_user.</param>
        /// <param name="satker_user">Initial value of satker_user.</param>
        /// <param name="email_user">Initial value of email_user.</param>
        /// <param name="password_user">Initial value of password_user.</param>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public static user Createuser(int id_user, string nama_user, string satker_user, string email_user, string password_user)
        {
            user user = new user();
            user.id_user = id_user;
            user.nama_user = nama_user;
            user.satker_user = satker_user;
            user.email_user = email_user;
            user.password_user = password_user;
            return user;
        }
        /// <summary>
        /// There are no comments for property id_user in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public int id_user
        {
            get
            {
                return this._id_user;
            }
            set
            {
                this.Onid_userChanging(value);
                this.ReportPropertyChanging("id_user");
                this._id_user = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("id_user");
                this.Onid_userChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private int _id_user;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_userChanging(int value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onid_userChanged();
        /// <summary>
        /// There are no comments for property nama_user in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string nama_user
        {
            get
            {
                return this._nama_user;
            }
            set
            {
                this.Onnama_userChanging(value);
                this.ReportPropertyChanging("nama_user");
                this._nama_user = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("nama_user");
                this.Onnama_userChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _nama_user;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onnama_userChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onnama_userChanged();
        /// <summary>
        /// There are no comments for property satker_user in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string satker_user
        {
            get
            {
                return this._satker_user;
            }
            set
            {
                this.Onsatker_userChanging(value);
                this.ReportPropertyChanging("satker_user");
                this._satker_user = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("satker_user");
                this.Onsatker_userChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _satker_user;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onsatker_userChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onsatker_userChanged();
        /// <summary>
        /// There are no comments for property email_user in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string email_user
        {
            get
            {
                return this._email_user;
            }
            set
            {
                this.Onemail_userChanging(value);
                this.ReportPropertyChanging("email_user");
                this._email_user = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("email_user");
                this.Onemail_userChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _email_user;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onemail_userChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onemail_userChanged();
        /// <summary>
        /// There are no comments for property password_user in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable=false)]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public string password_user
        {
            get
            {
                return this._password_user;
            }
            set
            {
                this.Onpassword_userChanging(value);
                this.ReportPropertyChanging("password_user");
                this._password_user = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false);
                this.ReportPropertyChanged("password_user");
                this.Onpassword_userChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private string _password_user;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onpassword_userChanging(string value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onpassword_userChanged();
        /// <summary>
        /// There are no comments for property jabatan_user in the schema.
        /// </summary>
        [global::System.Data.Objects.DataClasses.EdmScalarPropertyAttribute()]
        [global::System.Runtime.Serialization.DataMemberAttribute()]
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Nullable<int> jabatan_user
        {
            get
            {
                return this._jabatan_user;
            }
            set
            {
                this.Onjabatan_userChanging(value);
                this.ReportPropertyChanging("jabatan_user");
                this._jabatan_user = global::System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value);
                this.ReportPropertyChanged("jabatan_user");
                this.Onjabatan_userChanged();
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Nullable<int> _jabatan_user;
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onjabatan_userChanging(global::System.Nullable<int> value);
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        partial void Onjabatan_userChanged();
    }
    /// <summary>
    /// There are no comments for sifibiEntities in the schema.
    /// </summary>
    public partial class sifibiEntities : global::System.Data.Objects.ObjectContext
    {
        /// <summary>
        /// Initializes a new sifibiEntities object using the connection string found in the 'sifibiEntities' section of the application configuration file.
        /// </summary>
        public sifibiEntities() : 
                base("name=sifibiEntities", "sifibiEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new sifibiEntities object.
        /// </summary>
        public sifibiEntities(string connectionString) : 
                base(connectionString, "sifibiEntities")
        {
            this.OnContextCreated();
        }
        /// <summary>
        /// Initialize a new sifibiEntities object.
        /// </summary>
        public sifibiEntities(global::System.Data.EntityClient.EntityConnection connection) : 
                base(connection, "sifibiEntities")
        {
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// There are no comments for users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public global::System.Data.Objects.ObjectQuery<user> users
        {
            get
            {
                if ((this._users == null))
                {
                    this._users = base.CreateQuery<user>("[users]");
                }
                return this._users;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        private global::System.Data.Objects.ObjectQuery<user> _users;
        /// <summary>
        /// There are no comments for users in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")]
        public void AddTousers(user user)
        {
            base.AddObject("users", user);
        }
    }
}
